Repository boldlink/terraform-aws-eks, pull requests merged in 2023-07, with the labels that each got.

#25 [automation] updated files automatically.
  .github/workflows/auto-badge.yaml
  .github/workflows/checkov.yaml
  .github/workflows/pre-commit.yaml
Labels: automerge

#24 feature: Adding multiple changes
  .checkov.yaml
  .github/workflows/auto-badge.yaml
  .github/workflows/checkov.yaml
  .github/workflows/pre-commit.yaml
  CHANGELOG.md
  README.md
  examples/complete/README.md
  examples/complete/main.tf
  examples/minimum/README.md
  modules/fargate-profile/README.md
  modules/managed-node-group/README.md
  tests/supportingResources/README.md
  tests/supportingResources/data.tf
  tests/supportingResources/locals.tf
  tests/supportingResources/main.tf
  tests/supportingResources/variables.tf
Labels: minor

#27 fix: add missing oidc arn missing output
  CHANGELOG.md
  README.md
  examples/complete/README.md
  examples/minimum/README.md
  modules/fargate-profile/README.md
  modules/managed-node-group/README.md
  outputs.tf
  tests/supportingResources/README.md
Labels: patch
